"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](surface0)\
$os\
$username\
[](bg:path fg:surface0)\
$directory\
[](fg:path bg:git)\
$git_branch\
$git_status\
[](fg:git bg:languages)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:languages bg:docker)\
$docker_context\
[ ](fg:docker)\
$line_break$character"""

palette = 'nord'

[palettes.matte_black]
surface0 = "#313244"
base = "#1e1e2e"

path = "#ebb108"
git = "#d5840e"
languages = "#f00000"
docker = "#b81d1b"
text = "#cdd6f4"

[palettes.nord]
surface0 = "#4c566a"
base = "#1e1e2e"

path = "#81a1c1"
git = "#5e81ac"
languages = "#b48ead"
docker = "#8f6fa8"
text = "#cdd6f4"

[os]
disabled = false
style = "bg:surface0 fg:text"

[os.symbols]
Windows = "󰍲"
Arch = "󰣇"

[username]
show_always = true
style_user = "bg:surface0 fg:text"
style_root = "bg:surface0 fg:text"
format = '[ $user ]($style)'

[directory]
style = "fg:base bg:path"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documentos" = "󰈙 "
"Downloads" = " "
"Músicas" = "󰝚 "
"Imagens" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:git"
format = '[[ $symbol $branch ](fg:base bg:git)]($style)'

[git_status]
style = "bg:git"
format = '[[($all_status$ahead_behind )](fg:base bg:git)]($style)'

[nodejs]
symbol = ""
style = "bg:languages"
format = '[[ $symbol( $version) ](fg:base bg:languages)]($style)'

[c]
symbol = " "
style = "bg:languages"
format = '[[ $symbol( $version) ](fg:base bg:languages)]($style)'

[rust]
symbol = ""
style = "bg:languages"
format = '[[ $symbol( $version) ](fg:base bg:languages)]($style)'

[golang]
symbol = ""
style = "bg:languages"
format = '[[ $symbol( $version) ](fg:base bg:languages)]($style)'

[php]
symbol = ""
style = "bg:languages"
format = '[[ $symbol( $version) ](fg:base bg:languages)]($style)'

[java]
symbol = " "
style = "bg:languages"
format = '[[ $symbol( $version) ](fg:base bg:languages)]($style)'

[kotlin]
symbol = ""
style = "bg:languages"
format = '[[ $symbol( $version) ](fg:base bg:languages)]($style)'

[haskell]
symbol = ""
style = "bg:languages"
format = '[[ $symbol( $version) ](fg:base bg:languages)]($style)'

[python]
symbol = ""
style = "bg:languages"
format = '[[ $symbol( $version) ](fg:base bg:languages)]($style)'

[docker_context]
symbol = ""
style = "bg:docker"
format = '[[ $symbol( $context) ](fg:#83a598 bg:docker)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:git)'
error_symbol = '[](bold fg:languages)'
vimcmd_symbol = '[](bold fg:path)'
vimcmd_replace_one_symbol = '[](bold fg:path)'
vimcmd_replace_symbol = '[](bold fg:path)'
vimcmd_visual_symbol = '[](bold fg:path)'
