source = ~/.config/omarchy/current/theme/hyprlock.conf

general {
    ignore_empty_input = true
}

animations {
    enabled = false
}

background {
    color = $color
    monitor =
    path = ~/.config/omarchy/current/background
}

# ------------ Greetings and date. ------------

# Greetings.
label {
    monitor =
    text =Welcome!
    font_size = 55
    font_family = JetBrainsMono Nerd Font

    position = -630, 320
    halign = center
    valign = center
}

# Time.
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%H:%M")</span>"
    font_size = 40
    font_family = JetBrainsMono Nerd Font

    position = -630, 240
    halign = center
    valign = center
}

# Day - Month - Date.
label {
    monitor =
    text = cmd[update:60000] echo "<span>$(date +"%A, %d de %B" | perl -CS -Mutf8 -pe 's/^(.)/\U$1/')</span>"
    font_size = 20
    font_family = JetBrainsMono Nerd Font

    position = -630, 175
    halign = center
    valign = center
}

# ------------ User box config. ------------

shape {
    monitor =
    size = 320, 55
    color = rgba(255, 255, 255, .2)
    rounding = -1
    border_size = 0
    border_color = rgba(255, 255, 255, 1)
    rotate = 0
    xray = false # if true, make a "hole" in the background (rectangle of specified size, no rotation)

    position = -630, -140
    halign = center
    valign = center
}

label {
    monitor =
    text = $USER
    color = rgba(205, 214, 224, 0.80)
    font_size = 16
    font_family = JetBrainsMono Nerd Font

    position = -630, -140
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 320, 55
    position = -630, -220
    halign = center
    valign = center

    inner_color = rgba(255, 255, 255, 0.1)
    outer_color = rgba(255, 255, 255, 0)
    outline_thickness = 0
    
    font_family = JetBrainsMono Nerd Font
    font_color = rgb(205, 214, 244)
    
    placeholder_text = <i><span foreground="##ffffff99">Enter Password</span></i>
    check_color = $check_color
    fail_text = <i>$FAIL ($ATTEMPTS)</i>

    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true

    shadow_passes = 0
    fade_on_empty = false
}

auth {
    fingerprint:enabled = false
}
